### ISSUE TITLE
osc-paste fails on macos w/alacritty

### ISSUE THREAD

**Issue by theimpostor** [rumpelsepp/oscclip#46]
Clipboard contains the string `asdf`:

```
❯ osc-paste
Traceback (most recent call last):
  File "/Users/shoda/.local/bin/osc-paste", line 8, in <module>
    sys.exit(osc_paste())
             ^^^^^^^^^^^
  File "/Users/shoda/.local/pipx/venvs/oscclip/lib/python3.11/site-packages/oscclip/__init__.py", line 219, in osc_paste
    _osc_paste()
  File "/Users/shoda/.local/pipx/venvs/oscclip/lib/python3.11/site-packages/oscclip/__init__.py", line 203, in _osc_paste
    data = osc52_paste(args.primary)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shoda/.local/pipx/venvs/oscclip/lib/python3.11/site-packages/oscclip/__init__.py", line 118, in osc52_paste
    resp = read_tty(b"\a", 1)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/shoda/.local/pipx/venvs/oscclip/lib/python3.11/site-packages/oscclip/__init__.py", line 32, in read_tty
    sel.register(fd, selectors.EVENT_READ)
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/selectors.py", line 522, in register
    self._selector.control([kev], 0, 0)
OSError: [Errno 22] Invalid argument
^[]52;c;YXNkZgo=^G
```

Installed via pipx (`pipx install 'oscclip @ git+https://github.com/rumpelsepp/oscclip'`).

Versions:
```
❯ osc-copy --version
osc-copy 0.4.1

❯ alacritty --version
alacritty 0.12.2 (9d9982d)

❯ sw_vers
ProductName:	macOS
ProductVersion:	12.6.5
BuildVersion:	21G531
```

**Comment by rumpelsepp** [comment]
I cannot reproduce this on Gnome. Which compositor/Desktop Environment are you using?

**Comment by theimpostor** [comment]
I'm using macOS Monterey (that's the sw_vers output above)

**Comment by rumpelsepp** [comment]
Oh. I see. There is some platform stuff in the selector module. Need to think about this.

**Comment by rumpelsepp** [comment]
I rewrote this tool in Go. If this is still relevant for you, would you mind doing a short test?

```
$ make
$ ./osc-paste
```

I hope this will now just work on MAC.

**Comment by theimpostor** [comment]
`osc-copy` appears to work, however `osc-paste` seems to still be broken.

```
❯ ./osc-paste
illegal base64 data at input byte 0
❯ alacritty --version
alacritty 0.13.1 (fe2a3c5)
```

Alacritty recently made changes disabling paste by default, but I have it enabled in my config:

```
❯ rg -B 1 paste "${HOME}/.config/alacritty/alacritty.toml"
28-[terminal]
29:osc52 = "CopyPaste"
```

**Comment by theimpostor** [comment]
FYI I ended up writing a similar tool in go, inspired by your earlier python implmentation: [osc](https://github.com/theimpostor/osc). `osc paste` does work for me on mac.

Either way, thanks for your tool! My tmux support isn't as complete as yours, and it's on my list to add it.

**Comment by rumpelsepp** [comment]
I can reproduce this issue now! Trying to fix it.

edit: The OSC52 response from `tmux` (where I tested the tool) is different from `alacritty`:

```
In [4]: binascii.unhexlify("1b5d35323b633b5230597757564e4361475244516e4269626b49785a454e4361575659556d784a07")
Out[4]: b'\x1b]52;c;R0YwWVNCaGRDQnBibkIxZENCaWVYUmxJ\x07'

In [5]: binascii.unhexlify("1b5d35323b3b5230597757564e4361475244516e4269626b49785a454e4361575659556d784a07")
Out[5]: b'\x1b]52;;R0YwWVNCaGRDQnBibkIxZENCaWVYUmxJ\x07'
```

`tmux` leaves the source argument (-> the `c` between `;;`) empty.
